site_name: PQ Toolkit
site_url: https://vaiostar.github.io/pq-toolkit

dev_addr: '0.0.0.0:8000'
nav:
  - 'Home': index.md
  - 'Getting started':
    - 'Test types overview': getting-started/test-types-overview.md
    - 'Prerequisites': getting-started/prerequisites.md
  - 'Instalation and usage':
    - 'Python Plugin': instalation-and-usage/python-plugin.md
    - 'Web Aplication': instalation-and-usage/web-aplication.md
    - 'Troubleshooting': instalation-and-usage/troubleshooting.md 
  - 'Python API client reference':
    - 'API Client walkthrough': python-api-client/api-client-walkthrough.md
    - 'PqToolkitAPIClient Class': python-api-client/PqToolkitAPIClient.md
    - 'Exceptions': python-api-client/exceptions.md
    - 'Dataclasses': python-api-client/dataclasses.md
theme:
  name: material
  features:
    - content.tabs.link
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
- search
- termynal
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        paths: [../src/pq-toolkit]
        options:
          show_root_heading: true
          show_source: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
